steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aidashboard:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aidashboard:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'app'
      - 'deploy'
      - '--image-url=gcr.io/$PROJECT_ID/aidashboard:$COMMIT_SHA'
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/aidashboard:$COMMIT_SHA'

timeout: '1800s'